const privacy = [
  '1. Using this website (hereinafter - the Site) signifies User`s full and unconditional consent to this privacy policy and the purposes and conditions specified in it for processing one`s personal data.',
  '2. By posting resumes or other data on the Site, or by sending resumes or other similar letters to the email addresses of companies or other Users of the Site, Users of the Site voluntarily grant LLC "IT Jobs International" (hereinafter - the Company) as well as third parties who have access to this Site, their unconditional consent to process their personal data (contained in their resumes, messages, information collected or posted on the Site, and information sent to other Users of the Site) (hereinafter - Personal Data).',
  '3. Personal Data processing includes any action or set of actions associated with collecting, registering, accumulating, storing, adapting, modifying, updating, using and distributing (implementing, transferring), or deleting the Personal Data of the User in order to ensure the operation of services of the Site.',
  '4. The scope of the User`s Personal Data, in relation to which processing is carried out and which can be included in the personal data database (including in the resume personal data database), is defined as any information about the User posted in his or her resume or other data gathered or posted on the Site, as well as emails sent using it, which becomes known to the Company, as well as to any third parties using the site.',
  '5. By accepting this agreement, the User confirms that he or she understands all the rules of this Privacy Policy, as well as the purpose for collecting, storing, and processing his personal data. The User also agrees that the time period for processing his or her personal data does not have an expiration.',
  '6. The User has the right to change (update, supplement) the Personal Data, or parts of it, provided by him or her, as well as its privacy settings, at any time, using the function of editing and setting up access to personal information, as well as completely delete his or her account and Personal Data associated with the User from the Site database.',
  '7. The purpose for collecting, storing, and processing Personal Data is to provide the User with personalized Site services, including: access to a personalized dashboard; signing in; posting and sending resumes and jobs; processing User requests; and other services of the Site.',
];

export default privacy;
